### ISSUE TITLE
How to set "f", how to set different RKL/KL/JS divergence？

### ISSUE THREAD

**Issue by xiaoyuanzh** [fGAIL3456/fGAIL#2]
Hi, I notice you use 'type' in 'args' to set different kinds of divergence. But in the f-gail script. I notice you don't explicitly set a different kind of divergence. If I wanna use a specific kind of divergence. How to set?

Best,
Yuechao.

**Comment by fGAIL3456** [comment]
Hi Yuechao,

Thank you for pointing this out. I forgot to include other divergence implementations in this version, and will update later. 

For implementation of pre-defined divergences, such as the JS, KL, RKL and TV divergences, they all have explicit f function (generator functions) that can be found in https://en.wikipedia.org/wiki/F-divergence and in the paper https://arxiv.org/abs/1606.00709. Implement the convex conjugate of the predefined generator function f's and replace with the f_conjugate network will lead you to different divergences.

Many Thanks,
Xin Zhang
